from enum import IntEnum


class MessageType(IntEnum):
    ERROR = -1

    HELP = 0
    WRONG_START_COMMAND = 1
    WELCOME = 2
    TO_STATS = 3
    TO_EDIT = 4
    WEBSITE = 5

    STATS_TO_GAMES = 10
    STATS_TO_TRAININGS = 11
    STATS_TO_TIMEKEEPINGS = 12
    STATS_HANDLE_DOC_ID = 13
    STATS_OVERVIEW = 14

    CONTINUE_LATER = 42
    UNKNOWN_COMMAND = 43

