from enum import IntEnum


class Table(IntEnum):
    GAME_ATTENDANCE_TABLE = 0
    GAMES_TABLE = 1
    PLAYERS_TABLE = 2
    PLAYERS_TO_STATE_TABLE = 3
    TIMEKEEPING_ATTENDANCE_TABLE = 4
    TIMEKEEPING_TABLE = 5
    TRAINING_ATTENDANCE_TABLE = 6
    TRAININGS_TABLE = 7