from enum import IntEnum


class UserState(IntEnum):
    INIT = -1
    DEFAULT = 0

    STATS = 1
    STATS_TIMEKEEPINGS = 2
    STATS_TRAININGS = 3
    STATS_GAMES = 4

    EDIT = 10
    EDIT_TIMEKEEPINGS = 11
    EDIT_TRAININGS = 12
    EDIT_GAMES = 13

    ADMIN = 50
    ADMIN_ADD = 51
    ADMIN_UPDATE = 52
    ADMIN_UPDATE_GAME = 53
    ADMIN_UPDATE_TRAINING = 54
    ADMIN_UPDATE_TIMEKEEPING = 55

    ADMIN_UPDATE_GAME_LOCATION = 100
    ADMIN_UPDATE_GAME_OPPONENT = 101
    ADMIN_UPDATE_GAME_TIMESTAMP = 102

    ADMIN_UPDATE_TRAINING_LOCATION = 110
    ADMIN_UPDATE_TRAINING_TIMESTAMP = 112

    ADMIN_UPDATE_TIMEKEEPING_LOCATION = 120
    ADMIN_UPDATE_TIMEKEEPING_TIMESTAMP = 122

    ADMIN_STATISTICS = 130

    REJECTED = 999
