from enum import IntEnum


class UserState(IntEnum):
    INIT = -1
    DEFAULT = 0

    STATS = 1
    STATS_TIMEKEEPINGS = 2
    STATS_TRAININGS = 3
    STATS_GAMES = 4

    EDIT = 10
    EDIT_TIMEKEEPINGS = 11
    EDIT_TRAININGS = 12
    EDIT_GAMES = 13

    ADMIN = 50
    ADMIN_ADD = 51
    ADMIN_UPDATE = 52
    ADMIN_UPDATE_GAME = 53
    ADMIN_UPDATE_TRAINING = 54
    ADMIN_UPDATE_TIMEKEEPING = 55

    REJECTED = 999
